import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/footer";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import { ThemeProvider } from "../components/theme-provider";
import "./globals.css";
import { getCompetitions } from "@/data/competitions";
import { CompetitionsProvider } from "./context/CompetitionsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Football Schedule",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // コンペティションのデータを取得
  const competitionList = await getCompetitions();

  // サイドバーに必要なデータだけを抽出
  const sidebarData = competitionList.map((match) => ({
    id: match.id,
    competition: match.competition,
    competitionImg: match.competitionImg,
  }));

  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={cn(inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CompetitionsProvider value={{ competitionList }}>
            <Header />
            <Sidebar sidebarData={sidebarData} />
            {children}
            <Footer />
          </CompetitionsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
